version: "v1.0"
name: Using secrets in Semaphore 2.0
semaphore_image: standard
blocks:
- build:
      jobs:
        - name: My Semaphore 2.0 job
          commands:
            - echo $SECRET_ONE
            - echo "Hello World!"
            - echo $SEMAPHORE_PIPELINE_ID
      secrets:
        - name: mihalis-secrets
          env_var_names:
            - SECRET_ONE
